### ISSUE TITLE
不显示 日 啊

### ISSUE THREAD

**Issue by zhangchao828** [callmesoul/wepy-calendar#1]

**Comment by callmesoul** [comment]
什么需求？需要怎么显示日？

**Comment by zhangchao828** [comment]
![image](https://user-images.githubusercontent.com/15683846/37580667-eaed9174-2b7f-11e8-8d3f-193b7fee3c0f.png)
最后显示是这样的，下面空白，然后年月的滑动选择不流畅啊，划不动
你这个是根据https://github.com/treadpit/wx_calendar.git  这个改的吗

**Comment by callmesoul** [comment]
是不是没调用` this.$broadcast("startRenderCalendar"); ` 通知渲染。
我根据一个问答社区的 的代码改的，具体忘了。

**Comment by zhangchao828** [comment]
嗯嗯是的，不过我直接import canlendar from 'wepy-calendar'的时候报css找不到
![image](https://user-images.githubusercontent.com/15683846/37581219-8db8d98e-2b82-11e8-8a1d-e747f8ad8055.png)

我是把代码拷出来自己引用的才行

**Comment by callmesoul** [comment]
应该不会啊，是写在同一个页面的。而且我这边使用也正常啊。看下是不是其他问题

**Comment by zhangchao828** [comment]
日是固定写死的吗？比如切换到几几年2月份的时候，不应该有29,30,31号

**Comment by callmesoul** [comment]
不是写死的，是算出来的，就像2018年2月，是没有23，30，31的。正常的啊

**Comment by zhangchao828** [comment]
嗯，知道了，，每次改变日期之后还需要调用this.$broadcast("startRenderCalendar")才会变化 ，谢谢

**Comment by callmesoul** [comment]
对的，因为有些需要渲染打卡有些需要不需要，只好统一使用一个事件去通知
