### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by jackie007zzc** [callmesoul/wepy-calendar#2]
月份改变时，日期对应的星期几没有改变

**Comment by callmesoul** [comment]
能具体点？这边测试没问题

**Comment by moonwalkercui** [comment]
我已经修复，已经pull request

**Comment by callmesoul** [comment]
@moonwalkercui  没收到pull request

**Comment by ppjiucai** [comment]
![default](https://user-images.githubusercontent.com/20618898/46118769-c7285100-c23a-11e8-9c00-934c4a19821d.png)   像这个样初始第一天显示的日期数不正确，切换月份后才正确

**Comment by ppjiucai** [comment]
![default](https://user-images.githubusercontent.com/20618898/46118798-ede68780-c23a-11e8-962b-1a7026d4d57d.png)如图

**Comment by callmesoul** [comment]
@Caigengliang 我刚试了下是没问题的，是不是你传入的时间有问题？
最好能提供下代码

**Comment by Caigengliang** [comment]
@callmesoul 我是按照readme里面的demo试了下，代码如下，不知道哪里出了问题
<template>
    <wepyCanlendar
        :currentDate.sync="currentDate"
        :startDate.sync="startDate"
        :endDate.sync="endDate"
        :hasIconList.sync="hasIconList"
        :moduleId.sync="'step1Canlendar'"
    ></wepyCanlendar>
</template>
<script>
    import wepy from 'wepy'
    import wepyCanlendar from '@/components/calendar'

    export default class Index extends wepy.page {
      components = {
        wepyCanlendar
      };
      onLoad() {
        this.$broadcast('startRenderCalendar') // 通知日历组件可以开始渲染
      }
      data = {
        currentDate: '2018-08-09',
        startDate: '2018-01-01',
        endDate: '2018-02-01',
        hasIconList:[ '2018-06-01', '2018-06-06', '2018-06-09', '2018-06-10', '2018-06-15' ]
      };  // 页面所需数据均需在这里声明，可用于模板数据绑定
      events = {
        calChangeCurrentMonth: function (date, moduleId, e) {
        },
        calChangeSelectedDay: function (date, moduleId, e) {
        }
      };
    }
</script>

**Comment by ppjiucai** [comment]
@callmesoul 我是按照readme里面的demo试了下，代码如下，不知道哪里出了问题

- [ `<template>
    <wepyCanlendar
        :currentDate.sync="currentDate"
        :startDate.sync="startDate"
        :endDate.sync="endDate"
        :hasIconList.sync="hasIconList"
        :moduleId.sync="'step1Canlendar'"
    ></wepyCanlendar>
</template>
<script>
    import wepy from 'wepy'
    import wepyCanlendar from '@/components/calendar'

    export default class Index extends wepy.page {
      components = {
        wepyCanlendar
      };
      onLoad() {
        this.$broadcast('startRenderCalendar') // 通知日历组件可以开始渲染
      }
      data = {
        currentDate: '2018-08-09',
        startDate: '2018-01-01',
        endDate: '2018-02-01',
        hasIconList:[ '2018-06-01', '2018-06-06', '2018-06-09', '2018-06-10', '2018-06-15' ]
      };  // 页面所需数据均需在这里声明，可用于模板数据绑定
      events = {
        calChangeCurrentMonth: function (date, moduleId, e) {
        },
        calChangeSelectedDay: function (date, moduleId, e) {
        }
      };
    }
</script>
`

- 1.

**Comment by callmesoul** [comment]
@Caigengliang 是不是`startDate: '2018-01-01',` 和` endDate: '2018-02-01',`问题 ,你的当前时间不在之间，你试下这两个不要传进组件看可不可以
`<wepyCanlendar :currentDate.sync="currentDate" :hasIconList.sync="hasIconList"></wepyCanlendar>`

**Comment by Caigengliang** [comment]
@callmesoul 我试了下还是有这个问题，是框架的原因嘛
`<template>
<wepyCanlendar :currentDate.sync="currentDate" :hasIconList.sync="hasIconList"></wepyCanlendar>
</template>
<script>
    import wepy from 'wepy'
    import wepyCanlendar from '@/components/calendar'

    export default class Index extends wepy.page {
      components = {
        wepyCanlendar
      };
      onLoad() {
        this.$broadcast('startRenderCalendar') // 通知日历组件可以开始渲染
      }
      data = {
        currentDate: '2018-08-09',
        hasIconList: []
      };  // 页面所需数据均需在这里声明，可用于模板数据绑定
      events = {
        calChangeCurrentMonth: function (date, moduleId, e) {
        },
        calChangeSelectedDay: function (date, moduleId, e) {
        }
      };
    }
</script>
`

**Comment by ppjiucai** [comment]
@callmesoul 我试了下还是有这个问题，是框架的原因嘛
```
`<template>
<wepyCanlendar :currentDate.sync="currentDate" :hasIconList.sync="hasIconList"></wepyCanlendar>
</template>
<script>
    import wepy from 'wepy'
    import wepyCanlendar from '@/components/calendar'

    export default class Index extends wepy.page {
      components = {
        wepyCanlendar
      };
      onLoad() {
        this.$broadcast('startRenderCalendar') // 通知日历组件可以开始渲染
      }
      data = {
        currentDate: '2018-08-09',
        hasIconList: []
      };  // 页面所需数据均需在这里声明，可用于模板数据绑定
      events = {
        calChangeCurrentMonth: function (date, moduleId, e) {
        },
        calChangeSelectedDay: function (date, moduleId, e) {
        }
      };
    }
</script>
`
```

**Comment by callmesoul** [comment]
我把所有都删了了，跟你一样的currentDate，一样onLoad就` this.$broadcast('startRenderCalendar')`
都没问题啊。
你不是wepy框架？

**Comment by callmesoul** [comment]
看看是不是最新版本0.1.0

**Comment by ppjiucai** [comment]
wepy是最新的版本
![default](https://user-images.githubusercontent.com/20618898/46120853-c7791a00-c243-11e8-997c-8700fd80a568.png)

**Comment by ppjiucai** [comment]
我是这样的点击tarbar进到这个页面，然后初始的第一天显示的星期就不正确，切换月份回来后才正确。
![image](https://user-images.githubusercontent.com/20618898/46121433-42dbcb00-c246-11e8-9929-12c29f28f5fd.png)

**Comment by callmesoul** [comment]
我是说我这个插件的版本

**Comment by Caigengliang** [comment]
组件是最新的啊，进到这个页面，这个值没有改变成true，这个应该是，第一天前几天置空的标记把。

[图片]

**Comment by ppjiucai** [comment]
组件确实是最新的，我这个值，在页面打开时并没有变成true，切换日期时才会变成true
![image](https://user-images.githubusercontent.com/20618898/46122235-35c0db00-c24a-11e8-8a75-69f955c53b11.png)

**Comment by callmesoul** [comment]
应该是没执行到`startRenderCalendar`,你调试下看看哪里出问题了

**Comment by ppjiucai** [comment]
this.$broadcast('startRenderCalendar') 这个写在onShow里面就可以了，写在onLoad里面不行，虽然我不知道原因，不过解决了，谢谢大佬。

**Comment by callmesoul** [comment]
@Caigengliang 我写在onLoad也行啊，难道是tab问题？

**Comment by ppjiucai** [comment]
应该时app.wap里面的tabBar有影响。

**Comment by callmesoul** [comment]
应该是，没其他问题就关闭了
