### ISSUE TITLE
控件展示issue

### ISSUE THREAD

**Issue by murphy-yu** [callmesoul/wepy-calendar#5]
您好，本人小白，有个控件展示issue（按照'自定义参数'章节进行了1:！设置）：

![screen shot 2018-08-16 at 9 32 44 pm](https://user-images.githubusercontent.com/3724702/44211717-39b60380-a19c-11e8-883c-5eb77f4b07e4.png)
![screen shot 2018-08-16 at 9 32 51 pm](https://user-images.githubusercontent.com/3724702/44211724-3ae73080-a19c-11e8-9e81-44b87526eef4.png)

麻烦大神帮忙看一下，感谢！

**Comment by callmesoul** [comment]
@murphy-yu 不好意思，我完全不知道你说的是什么问题啊？麻烦写明问题，放上代码。

**Comment by lxljl** [comment]
@murphy-yu  你要通知 组件 可以渲染了 
 this.$broadcast("startRenderCalendar");//通知日历组件可以开始渲染

**Comment by murphy-yu** [comment]
@lxljl 感谢，solved as per suggestion
