### ISSUE TITLE
如何使用两次组件？

### ISSUE THREAD

**Issue by lxljl** [callmesoul/wepy-calendar#6]
选择开始日期，  到结束日期。
结束日期不能小于开始日期，  加上不可选日期。

**Comment by callmesoul** [comment]
@lxljl 之前并没有考虑到这问题。重复引用组件在wepy好像用的也是同一生命周期对象（也就是同一个组件），除非用repeat循环。
另外的实现思路为，加多个标示参数，例如随机生成一个uuid，然后传递到组件里。组件相应事件回调也带回uuid，然后根据uuid判断是否多次的调用

**Comment by lxljl** [comment]
@callmesoul  具体怎么操作 能否详细？
为了后续别的用户的需求，建议在README列出。当然 ，我先去自己研究下先，不会浪费维护者的时间。

**Comment by callmesoul** [comment]
@lxljl  比较简单，我就改了，checkout下0.1.0版本。readme也更新了

**Comment by lxljl** [comment]
@callmesoul   好的
